SELECT * FROM sakila.customer WHERE email LIKE 'LEONARD%';
SELECT * FROM sakila.customer WHERE (store_id = 2 and active IS false) AND first_name != 'KENNETH';
SELECT * FROM sakila.film WHERE replacement_cost > 18 AND rating != 'R' AND rating != 'NC-17' ORDER BY replacement_cost DESC, title LIMIT 100;
SELECT COUNT(*) FROM sakila.customer WHERE active IS TRUE;
SELECT * FROM sakila.customer WHERE store_id != 1;
SELECT * FROM sakila.film ORDER BY rental_rate, title LIMIT 50;
SELECT * FROM sakila.film WHERE title LIKE '%ace%';
SELECT * FROM sakila.film WHERE description LIKE '%china';
SELECT * FROM sakila.film WHERE description LIKE '%girl%' AND title LIKE '%lord';
SELECT * FROM sakila.film WHERE title LIKE '___gon%';
SELECT * FROM sakila.film WHERE title LIKE '___gon%' AND description LIKE '%Documentary%';
SELECT * FROM sakila.film WHERE title LIKE '%academy' OR title LIKE 'Mosquito%';
SELECT * FROM sakila.film WHERE description LIKE '%monkey%' AND description LIKE '%sumo%';
SELECT * FROM sakila.payment WHERE customer_id IN (269, 239, 126, 399, 142);
SELECT * FROM sakila.address WHERE district IN ('QLD', 'Nagasaki', 'California', 'Attika', 'Mandalay', 'Nantou', 'Texas');
SELECT * FROM sakila.customer WHERE last_name IN ('hicks', 'crawford', 'henry', 'boyd', 'mason', 'morales', 'kennedy') ORDER BY last_name;
SELECT * FROM sakila.address WHERE address_id BETWEEN 172 AND 176 ORDER BY address;
SELECT * FROM sakila.payment WHERE payment_date BETWEEN '2005-05-01' AND '2005-05-08';
SELECT * FROM sakila.film WHERE rental_duration BETWEEN 3 AND 6 ORDER BY rental_duration DESC, title;
SELECT * FROM sakila.film WHERE rating IN ('G', 'PG', 'PG-13') ORDER BY title LIMIT 500;
SELECT * FROM sakila.payment WHERE DATE(payment_date) = '2005-05-25';
SELECT * FROM sakila.payment WHERE DATE(payment_date) BETWEEN '2005-07-01' AND '2005-08-22';
SELECT DATE(rental_date), YEAR(rental_date), MONTH(rental_date), DAY(rental_date), HOUR(rental_date), MINUTE(rental_date) FROM sakila.rental WHERE rental_id = 10330;
SELECT * FROM sakila.payment WHERE DATE(payment_date) = '2005-07-28' AND HOUR(payment_date) >= 22;
SELECT * FROM sakila.payment WHERE DATE(payment_date) = '2005-07-28' AND HOUR(payment_date) >= 22 ORDER BY HOUR(payment_date), MINUTE(payment_date);
